export const searchEngines = [
  {
    category: '常规搜索',
    icon: '🌐',
    engines: [
      { id: 'bing', name: 'Bing', icon: '/ico/bing.ico', url: 'https://www.bing.com/search?q={query}' },
      { id: 'google', name: 'Google', icon: '/ico/google.ico', url: 'https://www.google.com/search?q={query}' },
      { id: 'baidu', name: '百度', icon: '/ico/baidu.ico', url: 'https://www.baidu.com/s?wd={query}' },
      { id: 'sogou', name: '搜狗', icon: '/ico/sogou.ico', url: 'https://www.sogou.com/web?query={query}' },
      { id: 'so', name: '360搜索', icon: '/ico/so.ico', url: 'https://www.so.com/s?q={query}' },
      { id: 'duckduckgo', name: 'DuckDuckGo', icon: '/ico/duckduckgo.ico', url: 'https://duckduckgo.com/?q={query}' },
      { id: 'yandex', name: 'Yandex', icon: '/ico/yandex.ico', url: 'https://yandex.com/search/?text={query}' },
      { id: 'startpage', name: 'Startpage', icon: '/ico/startpage.ico', url: 'https://www.startpage.com/do/search?q={query}' },
      { id: 'yahoo', name: 'Yahoo', icon: '/ico/yahoo.ico', url: 'https://search.yahoo.com/search?p={query}' },
    ],
  },
  {
    category: 'AI搜索',
    icon: '🤖',
    engines: [
      { id: 'searchgpt', name: 'SearchGPT', icon: '/ico/searchgpt.ico', url: 'https://chatgpt.com/?hints=search&q={query}' },
      { id: 'newbing', name: 'New Bing', icon: '/ico/newbing.ico', url: 'https://www.bing.com/search?q={query}&showconv=1' },
      { id: 'perplexity', name: 'Perplexity', icon: '/ico/perplexity.ico', url: 'https://www.perplexity.ai/search?q={query}' },
      { id: 'n', name: '纳米搜索', icon: '/ico/n.ico', url: 'https://www.n.cn/search?q={query}' },
      { id: 'metaso', name: '秘塔', icon: '/ico/metaso.ico', url: 'https://metaso.cn/?q={query}' },
      { id: 'andi', name: 'Andi', icon: '/ico/andisearch.ico', url: 'https://andisearch.com/search?q={query}' },
      { id: 'devv', name: 'Devv', icon: '/ico/devv.ico', url: 'https://devv.ai/search?q={query}' },
      { id: 'thinkany', name: 'ThinkAny', icon: '/ico/thinkany.ico', url: 'https://thinkany.so/search?q={query}' },
      { id: 'kaisouai', name: '开搜AI', icon: '/ico/kaisouai.ico', url: 'https://kaisouai.com/search?q={query}' },
      { id: 'webpilot', name: 'WebPilot', icon: '/ico/webpilot.ico', url: 'https://www.webpilot.ai/search?q={query}' },
      { id: 'consensus', name: 'Consensus', icon: '/ico/consensus.ico', url: 'https://consensus.app/search?q={query}' },
      { id: 'you', name: 'YOU', icon: '/ico/you.ico', url: 'https://you.com/search?q={query}' },
      { id: 'iask', name: 'iAsk.AI', icon: '/ico/iask.ai.ico', url: 'https://iask.ai/search?q={query}' },
      { id: 'phind', name: 'phind', icon: '/ico/phind.ico', url: 'https://www.phind.com/search?q={query}' },
    ],
  },
  {
    category: '社交搜索',
    icon: '👥',
    engines: [
      { id: 'xiaohongshu', name: '小红书', icon: '/ico/xiaohongshu.ico', url: 'https://www.xiaohongshu.com/search_result?keyword={query}' },
      { id: 'douyin', name: '抖音', icon: '/ico/douyin.ico', url: 'https://www.douyin.com/search/{query}' },
      { id: 'twitter', name: 'X', icon: '/ico/x.ico', url: 'https://twitter.com/search?q={query}' },
      { id: 'youtube', name: 'YouTube', icon: '/ico/youtube.ico', url: 'https://www.youtube.com/results?search_query={query}' },
      { id: 'v2ex', name: 'V2EX', icon: '/ico/sov2ex.ico', url: 'https://www.sov2ex.com/?q={query}' },
      { id: 'github', name: 'Github', icon: '/ico/github.ico', url: 'https://github.com/search?q={query}' },
      { id: 'producthunt', name: 'ProductHunt', icon: '/ico/producthunt.ico', url: 'https://www.producthunt.com/search?q={query}' },
      { id: 'jike', name: '即刻', icon: '/ico/okjike.ico', url: 'https://web.okjike.com/search?keyword={query}' },
      { id: 'facebook', name: 'FaceBook', icon: '/ico/facebook.ico', url: 'https://www.facebook.com/search/top/?q={query}' },
      { id: 'instagram', name: 'Instagram', icon: '/ico/instagram.ico', url: 'https://www.instagram.com/explore/tags/{query}/' },
      { id: 'bilibili', name: 'bilibili', icon: '/ico/bilibili.ico', url: 'https://search.bilibili.com/all?keyword={query}' },
      { id: 'zhihu', name: '知乎', icon: '/ico/zhihu.ico', url: 'https://www.zhihu.com/search?type=content&q={query}' },
      { id: 'weixin', name: '微信公众号', icon: '/ico/sogou.ico', url: 'https://weixin.sogou.com/weixin?type=2&query={query}' },
      { id: 'weibo', name: '微博', icon: '/ico/weibo.ico', url: 'https://s.weibo.com/weibo?q={query}' },
      { id: 'toutiao', name: '今日头条', icon: '/ico/toutiao.ico', url: 'https://so.toutiao.com/search?dvpf=pc&source=input&keyword={query}' },
    ],
  },
  {
    category: '网盘搜索',
    icon: '💾',
    engines: [
      { id: 'hunhepan', name: '混合盘', icon: '/ico/hunhepan.ico', url: 'https://hunhepan.com/search?keyword={query}' },
      { id: 'miaosou', name: '秒搜', icon: '/ico/miaosou.ico', url: 'https://miaosou.fun/search?q={query}' },
      { id: 'panso', name: '盘搜', icon: '/ico/panso.ico', url: 'https://panso.pro/search?q={query}' },
      { id: 'aliso', name: '阿里搜', icon: '/ico/aliso.ico', url: 'https://aliso.cc/search?q={query}' },
      { id: 'yunso', name: '小云搜索', icon: '/ico/yunso.ico', url: 'https://www.yunso.net/search?q={query}' },
      { id: 'quark', name: '夸克搜', icon: '/ico/quark.ico', url: 'https://www.quark.so/search?q={query}' },
      { id: 'dalipan', name: '大力盘', icon: '/ico/dalipan.ico', url: 'https://www.dalipan.com/search?keyword={query}' },
      { id: 'pansoso', name: '盘搜搜', icon: '/ico/pansoso.ico', url: 'https://pansoso.com/search?q={query}' },
      { id: 'lingfengyun', name: '凌风云', icon: '/ico/lingfengyun.ico', url: 'https://www.lingfengyun.com/search?wd={query}' },
    ],
  },
  {
    category: '动漫搜索',
    icon: '🎨',
    engines: [
      { id: 'acfun', name: 'AcFun', icon: '/ico/acfun.ico', url: 'https://www.acfun.cn/search?keyword={query}' },
      { id: 'pixiv', name: 'pixiv', icon: '/ico/pixiv.ico', url: 'https://www.pixiv.net/tags/{query}' },
      { id: 'huashi6', name: '触站', icon: '/ico/huashi6.ico', url: 'https://www.huashi6.com/search?q={query}' },
      { id: 'soman', name: '搜漫', icon: '/ico/soman.ico', url: 'https://www.soman.com/search.html?keyword={query}' },
      { id: 'manhuaren', name: '漫画人', icon: '/ico/manhuaren.ico', url: 'https://www.manhuaren.com/search?keywords={query}' },
      { id: 'qqcomic', name: '腾讯动漫', icon: '/ico/ac.qq.ico', url: 'https://ac.qq.com/Comic/searchList?search={query}' },
      { id: 'happymh', name: '嗨皮漫画', icon: '/ico/happymh.ico', url: 'https://m.happymh.com/search?keyword={query}' },
      { id: 'kuaikan', name: '快看漫画', icon: '/ico/kuaikanmanhua.ico', url: 'https://www.kuaikanmanhua.com/search?keyword={query}' },
      { id: 'bilibilimanga', name: '哔哩哔哩漫画', icon: '/ico/manga.bilibili.ico', url: 'https://manga.bilibili.com/search?keyword={query}' },
    ],
  },
  {
    category: '影视搜索',
    icon: '🎬',
    engines: [
      { id: 'youku', name: '优酷', icon: '/ico/youku.ico', url: 'https://so.youku.com/search_video/q_{query}' },
      { id: 'iqiyi', name: '爱奇艺', icon: '/ico/iqiyi.ico', url: 'https://so.iqiyi.com/so/q_{query}' },
      { id: 'qq', name: '腾讯视频', icon: '/ico/v.qq.ico', url: 'https://v.qq.com/x/search?q={query}' },
      { id: 'mgtv', name: '芒果TV', icon: '/ico/mgtv.ico', url: 'https://so.mgtv.com/so?k={query}' },
      { id: 'duanjuso', name: '短剧搜', icon: '/ico/duanjuso.ico', url: 'https://www.duanjuso.com/search?q={query}' },
      { id: 'kuakema', name: '夸克短剧', icon: '/ico/kuakema.ico', url: 'https://www.kuakema.com/search?q={query}' },
      { id: 'jpyy', name: '金牌影院', icon: '/ico/6umkq9b.ico', url: 'https://www.6umkq9b.com/search?q={query}' },
      { id: 'juyeye', name: '剧爷爷', icon: '/ico/juyeye.ico', url: 'https://www.juyeye.cc/search?q={query}' },
      { id: 'kuaisouxia', name: '快搜虾', icon: '/ico/kuaisouxia.ico', url: 'https://www.kuaisouxia.com/search?q={query}' },
    ],
  },
]

